export default {
  Aleksey_Natekin: {
    id: 'Aleksey_Natekin',
    img: '/speakers/Aleksey_Natekin.jpg',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'Aleksey Natekin',
    position: 'Dictator / Founder at Data Souls, ODS.ai',
    topic: '',
    socialUrls: [
      'https://github.com/natekin',
      'https://ru.linkedin.com/in/natekin',
    ],
  },
  Manvel_Avetissian: {
    id: 'Manvel_Avetissian',
    img: '/speakers/Manvel_Avetissian.jpeg',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'Manvel Avetissian',
    position: 'Managing Director at Sberbank AI Lab',
    topic: '',
    socialUrls: [
      'https://github.com/mnvl',
      'https://ru.linkedin.com/in/manvelavetisian',
    ],
  },
  Vahe_Hakobyan: {
    id: 'Vahe_Hakobyan',
    img: '/speakers/Vahe_Hakobyan.jpg',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'Vahe Hakobyan',
    position: 'Senior Research Engineer at Zalando',
    topic: '',
    socialUrls: [
      'https://github.com/cryptexis',
      'https://de.linkedin.com/in/vahe-v-hakobyan',
    ],
  },
  Hrayr_Harutyunyan: {
    id: 'Hrayr_Harutyunyan',
    img: '/speakers/Hrayr_Harutyunyan.png',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'Hrayr Harutyunyan',
    position: 'PhD student at University of Southern California',
    topic: '',
    socialUrls: [
      'https://github.com/hrayrhar',
      'https://scholar.google.com/citations?hl=en&user=GaCGz8wAAAAJ',
    ],
  },
  Shushan_Arakelyan: {
    id: 'Shushan_Arakelyan',
    img: '/speakers/Shushan_Arakelyan.jfif',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'Shushan Arakelyan',
    position: 'PhD student at University of Southern California',
    topic: '',
    socialUrls: [
      'https://github.com/ShushanArakelyan',
      'https://www.linkedin.com/in/arakelyanshushan',
      'https://scholar.google.co.uk/citations?user=xqZY5lMAAAAJ&hl=en',
    ],
  },
  Levan_Tsinadze: {
    id: 'Levan_Tsinadze',
    img: '/speakers/Levan_Tsinadze.png',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'Levan Tsinadze',
    position: 'Head of AI at Maxin.ai',
    topic: '',
    socialUrls: [
      'https://github.com/levants',
      'https://www.linkedin.com/in/levan-tsinadze-246a1b2a/',
    ],
  },
  George_Kasparyants: {
    id: 'George_Kasparyants',
    img: '/speakers/George_Kasparyants.jfif',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'George Kasparyants',
    position: 'Head of AI at Gradient',
    topic: '',
    socialUrls: [
      'https://github.com/DELTA37',
      'https://www.linkedin.com/in/george-kasparyants-579bb4129',
    ],
  },
  Hrant_Khachatrian: {
    id: 'Hrant_Khachatrian',
    img: '/speakers/Hrant_Khachatrian.jpg',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'Hrant Khachatrian',
    position: 'Director at YerevaNN',
    topic: '',
    socialUrls: [
      'https://github.com/Hrant-Khachatrian',
      'https://scholar.google.com/citations?user=CxOrE_kAAAAJ&hl=en',
    ],
  },
  Arsen_Yeghiazaryan: {
    id: 'Arsen_Yeghiazaryan',
    img: '/speakers/Arsen_Yeghiazaryan.jfif',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'Arsen Yeghiazaryan',
    position: 'ML Team Lead at Webb Fontaine',
    topic: '',
    socialUrls: [
      'https://www.linkedin.com/in/arsen-yeghiazaryan-9abb4721',
    ],
  },
  Andranik_Khachatryan: {
    id: 'Andranik_Khachatryan',
    img: '/speakers/Andranik_Khachatryan.jpg',
    imgSmall: '/speakers-small/Jesse_Martin.png',
    name: 'Andranik Khachatryan',
    position: 'ML Specialist, Consultant',
    topic: '',
    socialUrls: [
      'https://github.com/ando-khachatryan',
      'https://www.linkedin.com/in/andranik-khachatryan-4b6b82145',
    ],
  },
};
